import type { Metadata } from "next";
import { Alice, Poppins } from "next/font/google";
import "./globals.css";

// Alice font setup
const alice = Alice({
  weight: "400",
  variable: "--font-alice",
  subsets: ["latin"],
});

// Poppins font setup
const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Escape Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alice.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
